### ISSUE TITLE
Add Wake-On-Lan to TitanX

### ISSUE THREAD

**Issue by PeterBowman** [jgvictores/jgvictores.github.io#6]
Last night I forgot to leave the TitanX PC on - I'm sorry if this causes any inconvenience or disruption to someone's workflow until Monday. I was advised to open this issue as a countermeasure for future incidents of this kind.

**Comment by jgvictores** [comment]
Took note on personal agenda! Closing to keep this repo clean from whatever is not related to its contents, sorry for the misunderstanding! : )
